.classpath
.project
src/main/java/com/hanul/anafor/ScheduleController.java
src/main/resources/sqlmap/schedule-mapper.xml

05 24 19:24 박천일 최종본

---

src/main/java/com/hanul/anafor/PillController.java
src/main/resources/sqlmap/pill-mapper.xml

0525 QR delete

---

src/main/java/com/hanul/anafor/SearchController.java
src/main/resources/sqlmap/search-mapper.xml

05 25 19:40 박천일 최종본

---

src/main/java/com/hanul/anafor/SearchController.java
src/main/resources/sqlmap/search-mapper.xml
src/main/resources/sqlmap/user-mapper.xml

18 : 00 박천일 최종본

---

src/main/java/com/hanul/anafor/Web_NoticeController.java
src/main/java/web_notice/NoticeDAO.java
src/main/java/web_notice/NoticeService.java
src/main/java/web_notice/NoticeServiceImpl.java
src/main/java/web_notice/NoticeVO.java
src/main/resources/sqlmap/notice-mapper.xml
src/main/webapp/WEB-INF/spring/root-context.xml
src/main/webapp/WEB-INF/views/notice/list.jsp
src/main/webapp/WEB-INF/views/notice/new.jsp
src/main/webapp/resources/css/common.css

공지사항 리스트조회

---

src/main/webapp/WEB-INF/views/home.jsp

06.02 ljm 오전

---

src/main/java/com/hanul/anafor/Web_CustomerController.java
src/main/java/com/hanul/anafor/Web_NoticeController.java
src/main/java/com/hanul/anafor/Web_UserController.java
src/main/java/web_customer/CustomerDAO.java
src/main/java/web_customer/CustomerService.java
src/main/java/web_customer/CustomerServiceImpl.java
src/main/java/web_customer/CustomerVO.java
src/main/java/web_notice/NoticeDAO.java
src/main/java/web_notice/NoticeServiceImpl.java
src/main/resources/sqlmap/customer-mapper.xml
src/main/webapp/WEB-INF/spring/root-context.xml
src/main/webapp/WEB-INF/views/customer/detail.jsp
src/main/webapp/WEB-INF/views/customer/list.jsp
src/main/webapp/WEB-INF/views/notice/detail.jsp
src/main/webapp/WEB-INF/views/notice/list.jsp
src/main/webapp/WEB-INF/views/notice/new.jsp
src/main/webapp/resources/css/common.css

Q&A, 공지사항 

---

src/main/java/com/hanul/anafor/Web_CustomerController.java
src/main/java/com/hanul/anafor/Web_boxController.java
src/main/java/common/PageVO.java
src/main/java/web_customer/CustomerDAO.java
src/main/java/web_customer/CustomerServiceImpl.java
src/main/resources/sqlmap/customer-mapper.xml
src/main/webapp/WEB-INF/views/customer/list.jsp
src/main/webapp/WEB-INF/views/customer/new.jsp
src/main/webapp/resources/css/common.css

고객센터 레이아웃 수정작업중

---

src/main/java/web_customer/CustomerDAO.java
src/main/java/web_notice/NoticeDAO.java
src/main/resources/sqlmap/wcustomer-mapper.xml
src/main/resources/sqlmap/wnotice-mapper.xml
src/main/webapp/WEB-INF/views/customer/detail.jsp
src/main/webapp/WEB-INF/views/customer/list.jsp
src/main/webapp/WEB-INF/views/customer/new.jsp
src/main/webapp/WEB-INF/views/notice/detail.jsp
src/main/webapp/WEB-INF/views/notice/list.jsp
src/main/webapp/WEB-INF/views/notice/new.jsp
src/main/webapp/resources/css/common.css

web 맵퍼 이름 w 추가 변경
게시판 가운데정렬...
common.css 정렬

공지사항게시판 정렬

---

src/main/java/com/hanul/anafor/AdminController.java
src/main/webapp/WEB-INF/views/admin/dashboard.jsp
src/main/webapp/WEB-INF/views/home.jsp
src/main/webapp/WEB-INF/views/include/header.jsp
src/main/webapp/WEB-INF/views/tiles/layout.jsp
src/main/webapp/resources/css/common.css
src/main/webapp/resources/js/admin.js

06.02 ljm 최종

---

src/main/webapp/WEB-INF/views/shop/order.jsp
src/main/webapp/WEB-INF/views/shop/shop.jsp

06 03 스프링 최종

---

src/main/webapp/WEB-INF/views/shop/order.jsp
src/main/webapp/resources/css/common.css

06 05 18:00 최종

---

.classpath
src/main/java/web_shop_detail/ShopDetailDAO.java
src/main/java/web_shop_detail/ShopDetailService.java
src/main/java/web_shop_detail/ShopDetailServiceImpl.java
src/main/java/web_shop_detail/ShopDetailVO.java
src/main/webapp/WEB-INF/views/shop/order.jsp

06 06 19:06 최종

---

src/main/java/com/hanul/anafor/Web_CustomerController.java
src/main/java/web_customer/CustomerVO.java
src/main/resources/sqlmap/wcustomer-mapper.xml
src/main/webapp/WEB-INF/views/admin_contents/list.jsp
src/main/webapp/WEB-INF/views/customer/q_detail.jsp
src/main/webapp/WEB-INF/views/customer/q_list.jsp
src/main/webapp/WEB-INF/views/customer/q_modify.jsp
src/main/webapp/WEB-INF/views/customer/q_new.jsp
src/main/webapp/WEB-INF/views/notice/detail.jsp

큐앤에이 카테고리 추가

---

src/main/java/com/hanul/anafor/My_QnaController.java
src/main/java/my_qna/MyqDAO.java
src/main/java/my_qna/MyqPage.java
src/main/java/my_qna/MyqService.java
src/main/java/my_qna/MyqServiceImpl.java
src/main/java/my_qna/MyqVO.java
src/main/resources/sqlmap/ad_contents-mapper.xml
src/main/resources/sqlmap/my_qna-mapper.xml
src/main/webapp/WEB-INF/spring/root-context.xml
src/main/webapp/WEB-INF/views/admin_contents/detail.jsp
src/main/webapp/WEB-INF/views/admin_contents/list.jsp
src/main/webapp/WEB-INF/views/customer/q_list.jsp
src/main/webapp/WEB-INF/views/include/mymenu.jsp
src/main/webapp/WEB-INF/views/include/page.jsp
src/main/webapp/WEB-INF/views/my_qna/list.jsp
src/main/webapp/WEB-INF/views/notice/list.jsp
src/main/webapp/WEB-INF/views/tiles/mypage_layout.jsp

마이페이지 작업중입니다

---

src/main/webapp/WEB-INF/views/admin_contents/detail.jsp
src/main/webapp/WEB-INF/views/customer/q_detail.jsp

게시판 목록으로 수정

---

src/main/webapp/WEB-INF/views/admin_contents/list.jsp

list 셀렉트 정렬

---

src/main/java/com/hanul/anafor/My_ShopController.java
src/main/java/com/hanul/anafor/Web_BoxController.java
src/main/java/my_shop/my_ShopDAO.java
src/main/java/my_shop/my_ShopService.java
src/main/java/my_shop/my_ShopServiceImpl.java
src/main/resources/sqlmap/my_shop-mapper.xml
src/main/webapp/WEB-INF/views/admin_shop/shopDetail.jsp
src/main/webapp/WEB-INF/views/my_shop/shopList.jsp

16: 23 최종본

---

src/main/resources/sqlmap/wuser-mapper.xml
src/main/webapp/WEB-INF/views/admin_user/manageUser.jsp
src/main/webapp/WEB-INF/views/my_info/info.jsp
src/main/webapp/resources/js/join-check.js

회원페이지 유효성 검사, 관리자페이지 페이징 오류 수정

0616 마이페이지 관리자페이지 회원관리 수정

---

src/main/java/com/hanul/anafor/IoTController.java
src/main/java/web_customer/CustomerVO.java
src/main/resources/sqlmap/IoT-mapper.xml
src/main/webapp/WEB-INF/views/admin_contents/new.jsp
src/main/webapp/WEB-INF/views/customer/f_list.jsp
src/main/webapp/WEB-INF/views/customer/q_detail.jsp
src/main/webapp/WEB-INF/views/customer/q_list.jsp
src/main/webapp/WEB-INF/views/customer/q_new.jsp
src/main/webapp/WEB-INF/views/my_qna/list.jsp
src/main/webapp/WEB-INF/views/notice/list.jsp

게시판 디테일 작업중

---

src/main/java/com/hanul/anafor/Web_CustomerController.java
src/main/resources/sqlmap/wcustomer-mapper.xml
src/main/webapp/WEB-INF/views/admin_contents/detail.jsp
src/main/webapp/WEB-INF/views/admin_contents/list.jsp
src/main/webapp/WEB-INF/views/admin_contents/modify.jsp
src/main/webapp/WEB-INF/views/admin_contents/new.jsp
src/main/webapp/WEB-INF/views/customer/f_list.jsp
src/main/webapp/WEB-INF/views/customer/q_list.jsp
src/main/webapp/WEB-INF/views/my_qna/list.jsp

고객센터 Q&A 수정

---

src/main/webapp/WEB-INF/views/admin_contents/list.jsp
src/main/webapp/WEB-INF/views/admin_shop/shopList.jsp
src/main/webapp/WEB-INF/views/include/header.jsp
src/main/webapp/WEB-INF/views/my_shop/shopList.jsp
src/main/webapp/WEB-INF/views/shop/order.jsp
src/main/webapp/WEB-INF/views/shop/shop.jsp
src/main/webapp/WEB-INF/views/tiles/admin_layout.jsp

min-height 적용

---

src/main/java/com/hanul/anafor/My_ShopController.java
src/main/java/my_shop/my_ShopDAO.java
src/main/java/my_shop/my_ShopService.java
src/main/java/my_shop/my_ShopServiceImpl.java
src/main/java/web_shop/ShopService.java
src/main/resources/sqlmap/my_shop-mapper.xml
src/main/webapp/WEB-INF/views/admin_shop/shopList.jsp
src/main/webapp/WEB-INF/views/my_shop/shopDetail.jsp
src/main/webapp/WEB-INF/views/my_shop/shopList.jsp
src/main/webapp/WEB-INF/views/my_shop/shopModify.jsp
src/main/webapp/WEB-INF/views/shop/shop.jsp

12 : 32 스프링 수정

---

src/main/java/com/hanul/anafor/ScheduleController.java
src/main/webapp/WEB-INF/views/include/header.jsp

17 : 48 스프링 최종

---

src/main/java/IoT/IoTVO.java
src/main/java/com/hanul/anafor/IoTController.java
src/main/java/user/UserVO.java
src/main/resources/sqlmap/IoT-mapper.xml
src/main/resources/sqlmap/user-mapper.xml
src/main/webapp/WEB-INF/views/notice/list.jsp

iot box_id-> no변경

---

src/main/java/web_shop/ShopDetailVO.java
src/main/webapp/WEB-INF/views/admin_shop/shopList.jsp
src/main/webapp/WEB-INF/views/my_shop/shopModify.jsp

13 : 03 스프링 수정

---

src/main/webapp/WEB-INF/views/admin_shop/shopList.jsp
src/main/webapp/WEB-INF/views/my_shop/shopDetail.jsp
src/main/webapp/WEB-INF/views/my_shop/shopModify.jsp
src/main/webapp/WEB-INF/views/shop/shop.jsp
src/main/webapp/resources/css/common.css

스프링 최종 20 : 00

---

src/main/webapp/WEB-INF/views/include/header.jsp

고객센터페이지 첫화면 faq로변경
